name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: "21"
        distribution: "temurin"
        cache: maven
    
    - name: Run Service Tests
      run: |
        echo "Running Service Tests..."
        mvn -B test -Dtest=**/*ServiceTest.java -DfailIfNoTests=false
      env:
        SPRING_PROFILES_ACTIVE: test
        MY_KEY: ${{ secrets.MY_KEY }}
    
    - name: Run Repository Integration Tests
      run: |
        echo "Running Repository Integration Tests..."
        mvn -B test -Dtest=**/*RepositoryIntegrationTest.java -DfailIfNoTests=false
      env:
        SPRING_PROFILES_ACTIVE: test
        MY_KEY: ${{ secrets.MY_KEY }}
    
    - name: Run Controller Tests
      run: |
        echo "Running Controller Tests..."
        mvn -B test -Dtest=**/*ControllerTest.java -DfailIfNoTests=false
      env:
        SPRING_PROFILES_ACTIVE: test
        MY_KEY: ${{ secrets.MY_KEY }}
        SPRING_MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
        SPRING_MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
    
    - name: Run Application Tests
      run: |
        echo "Running Application Tests..."
        mvn -B test -Dtest=**/TrabajoYaApplicationTests.java -DfailIfNoTests=false
      env:
        SPRING_PROFILES_ACTIVE: test
        MY_KEY: ${{ secrets.MY_KEY }}
    
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          target/surefire-reports/
          target/failsafe-reports/

    - name: Upload Coverage Report
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: target/site/jacoco/

    - name: Check Test Results
      if: failure()
      run: |
        echo "::error::Tests failed! Check the test results for more details."
        echo "=== Service Tests ==="
        cat target/surefire-reports/TEST-*ServiceTest.xml || true
        echo "=== Repository Integration Tests ==="
        cat target/surefire-reports/TEST-*RepositoryIntegrationTest.xml || true
        echo "=== Controller Tests ==="
        cat target/surefire-reports/TEST-*ControllerTest.xml || true
        echo "=== Application Tests ==="
        cat target/surefire-reports/TEST-*ApplicationTests.xml || true
        exit 1
